version: "3.3"
services:
  social-graph-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: social-graph-service
    depends_on:
      - jaeger-agent
      - social-graph-mongodb
    restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./config:/social-network-microservices/config

  social-graph-mongodb:
    image: mongo:4.4.6
    hostname: social-graph-mongodb
    restart: always

  social-graph-redis:
    image: redis
    hostname: social-graph-redis
    restart: always

  home-timeline-redis:
    image: redis
    hostname: home-timeline-redis
    restart: always

  compose-post-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: compose-post-service
    restart: always
    depends_on:
      - jaeger-agent
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config

  post-storage-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: post-storage-service
    ports:
      - 10002:9090
    restart: always
    depends_on:
      - jaeger-agent
      - post-storage-mongodb
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config

  post-storage-memcached:
    image: memcached
    hostname: post-storage-memcached
    restart: always

  post-storage-mongodb:
    image: mongo:4.4.6
    hostname: post-storage-mongodb
    restart: always

  user-timeline-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-timeline-service
    restart: always
    depends_on:
      - jaeger-agent
      - user-timeline-mongodb
    entrypoint: UserTimelineService
    volumes:
      - ./config:/social-network-microservices/config

  user-timeline-redis:
    image: redis
    hostname: user-timeline-redis
    restart: always

  user-timeline-mongodb:
    image: mongo:4.4.6
    hostname: user-timeline-mongodb
    restart: always

  url-shorten-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: url-shorten-service
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      - jaeger-agent
      - url-shorten-mongodb
    volumes:
      - ./config:/social-network-microservices/config

  url-shorten-memcached:
    image: memcached
    hostname: url-shorten-memcached
    restart: always

  url-shorten-mongodb:
    image: mongo:4.4.6
    hostname: url-shorten-mongodb
    restart: always

  user-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-service
    restart: always
    depends_on:
      - jaeger-agent
      - user-mongodb
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config

  user-memcached:
    image: memcached
    hostname: user-memcached
    restart: always

  user-mongodb:
    image: mongo:4.4.6
    hostname: user-mongodb
    restart: always

  media-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: media-service
    depends_on:
      - jaeger-agent
      - media-mongodb
    restart: always
    entrypoint: MediaService
    volumes:
      - ./config:/social-network-microservices/config

  media-memcached:
    image: memcached
    hostname: media-memcached
    restart: always

  media-mongodb:
    image: mongo:4.4.6
    hostname: media-mongodb
    restart: always

  text-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: text-service
    restart: always
    depends_on:
      - jaeger-agent
    entrypoint: TextService
    volumes:
      - ./config:/social-network-microservices/config

  unique-id-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: unique-id-service
    restart: always
    depends_on:
      - jaeger-agent
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config

  user-mention-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-mention-service
    depends_on:
      - jaeger-agent
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config

  home-timeline-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: home-timeline-service
    depends_on:
      - jaeger-agent
    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config

  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    depends_on:
      - jaeger-agent
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift

  media-frontend:
    image: yg397/media-frontend:xenial
    hostname: media-frontend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - jaeger-agent
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  jaeger-agent:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
